export const AUTH_ACTIONS = {
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT"
};

export const USER_ACTION = {
  GET_USER_BY_EMAIL: "GET_USER_BY_EMAIL"
};

export const DATA_ACTION = {
  INSERT_CLASSIFICATION: "INSERT_CLASSIFICATION",
  GET_CLASSIFICATION: "GET_CLASSIFICATION"
};

export const TIMER_ACTION = {
  TIME_START: "TIME_START",
  TIME_END: "TIME_END"
};

export const CHALLENGE_ACTION = {
  CREATE_NEW_CHALLENGE: "CREATE_NEW_CHALLENGE",
  TEST_NEW_CODE: "TEST_NEW_CODE",
  START_TEST_NEW_CODE: "START_TEST_NEW_CODE",
  FINISH_TEST_NEW_CODE: "FINISH_TEST_NEW_CODE",
  GET_CHALLENGE: "GET_CHALLENGE",
  CLEAR_CHALLENGE: "CLEAR_CHALLENGE"
};

export const UI_ACTIONS = {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  UI_SIDE_MENU: "OPEN_MENU",
  UI_LOADING: "UI_LOADING",
  ADD_TOASTER_ALERT: "ADD_TOASTER_ALERT",
  REMOVE_TOASTER_ALERT: "REMOVE_TOASTER_ALERT",
  SHOW_LOGIN: "SHOW_LOGIN",
  NAVIGATE_HOME: "NAVIGATE_HOME",
  TRACK_ROUTE: "TRACK_ROUTE"
};
